package dev.version1.cabinet.enums;

public enum ReasonOfAppointment {
    GENERAL_CHECKUP,
    CONSULTATION,
    FOLLOW_UP,
    DIAGNOSTIC_TEST,
    VACCINATION,
    MEDICATION_REFILL,
    PAIN_MANAGEMENT,
    SURGERY_CONSULTATION,
    PRENATAL_CARE,
    POSTNATAL_CARE,
    DENTAL_CHECKUP,
    EYE_EXAM,
    HEARING_TEST,
    ALLERGY_TEST,
    PHYSICAL_THERAPY,
    PSYCHOTHERAPY,
    MENTAL_HEALTH_EVALUATION,
    NUTRITION_COUNSELING,
    PREVENTIVE_CARE,
    EMERGENCY,
    OTHER

}
