package dev.version1.cabinet.enums;

public enum SurgeryType {
    GENERAL_SURGERY,
    ORTHOPEDIC_SURGERY,
    NEUROSURGERY,
    CARDIAC_SURGERY,
    PLASTIC_SURGERY,
    OPHTHALMIC_SURGERY,
    GYNECOLOGIC_SURGERY,
    UROLOGIC_SURGERY,
    OTOLARYNGOLOGY,
    PEDIATRIC_SURGERY,
    VASCULAR_SURGERY,
    THORACIC_SURGERY,
    MAXILLOFACIAL_SURGERY,
    ORAL_SURGERY,
    ONCOLOGIC_SURGERY,
    TRANSPLANT_SURGERY,
    DERMATOLOGIC_SURGERY,
    ENDOSCOPIC_SURGERY,
    MINIMALLY_INVASIVE_SURGERY,
    ROBOTIC_SURGERY,
    OTHER
}
